"""
Pydantic schemas for the CI/CD maintenance agent.

Defines models for coupling analysis, architectural drift detection,
and automated refactoring proposals.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class DriftType(StrEnum):
    """Types of architectural drift."""

    COUPLING_INCREASE = "COUPLING_INCREASE"
    CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY"
    GOD_MODULE = "GOD_MODULE"
    DEAD_CODE = "DEAD_CODE"
    CONVENTION_VIOLATION = "CONVENTION_VIOLATION"


class DriftSeverity(StrEnum):
    """Severity of architectural drift."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FileCoupling(BaseModel):
    """Coupling relationship between two files."""

    file_a: str
    file_b: str
    coupling_score: float = Field(ge=0, le=1.0)
    shared_symbols: list[str] = Field(default_factory=list)
    change_frequency: int = Field(
        default=0,
        ge=0,
        description="Number of times these files were changed together.",
    )


class CouplingReport(BaseModel):
    """Result of coupling analysis on a codebase."""

    repository: str
    analyzed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    total_files: int = 0
    total_modules: int = 0
    file_couplings: list[FileCoupling] = Field(default_factory=list)
    average_coupling: float = Field(default=0.0, ge=0, le=1.0)
    hotspots: list[str] = Field(
        default_factory=list,
        description="Files with the highest coupling (top 10%).",
    )
    recommendations: list[str] = Field(default_factory=list)


class DriftAlert(BaseModel):
    """An architectural drift alert."""

    alert_id: str
    component: str
    drift_type: DriftType
    severity: DriftSeverity
    description: str
    suggested_action: str
    detected_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = Field(default_factory=dict)


class RefactorProposal(BaseModel):
    """A proposed refactoring generated by the LLM maintenance agent."""

    proposal_id: str
    title: str
    description: str
    files_affected: list[str] = Field(default_factory=list)
    diff_preview: str = Field(
        default="",
        description="A unified diff preview of the proposed changes.",
    )
    confidence: float = Field(ge=0, le=1.0)
    estimated_effort: str = Field(
        default="",
        description="Estimated effort (e.g., 'small', 'medium', 'large').",
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    status: str = Field(default="pending")
    approved_by: str | None = None
    approved_at: datetime | None = None


class AnalyzeRequest(BaseModel):
    """Request to trigger a coupling analysis."""

    repository_path: str = Field(
        default=".",
        description="Path to the repository to analyze.",
    )
    include_patterns: list[str] = Field(
        default_factory=lambda: ["*.py"],
        description="File glob patterns to include in analysis.",
    )
    exclude_patterns: list[str] = Field(
        default_factory=lambda: ["**/test_*", "**/__pycache__/*", "**/venv/*"],
        description="File glob patterns to exclude.",
    )
