"""
GitHub Integration Service — adapter for automated branch, commit, and PR generation.

Provides a clean interface for interacting with Git providers (GitHub) to push
refactoring proposals generated by the maintenance agent.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from typing import Any

import structlog

logger = structlog.get_logger()


class GitProviderAdapter(ABC):
    """Abstract base class for Git provider interactions."""

    @abstractmethod
    async def create_branch(self, branch_name: str) -> None:
        """Create a new branch from the default branch."""
        pass

    @abstractmethod
    async def commit_changes(
        self,
        branch_name: str,
        commit_message: str,
        file_changes: dict[str, str],
    ) -> None:
        """Commit multiple file changes to a branch."""
        pass

    @abstractmethod
    async def create_pull_request(
        self,
        branch_name: str,
        title: str,
        body: str,
    ) -> str:
        """Create a pull request and return its URL."""
        pass


class GitHubAdapter(GitProviderAdapter):
    """Concrete Git provider implementation for GitHub using PyGithub."""

    def __init__(
        self,
        repo_name: str | None = None,
        token: str | None = None,
        dry_run: bool = True,
    ) -> None:
        self.dry_run = dry_run
        self.repo_name = repo_name or os.environ.get("GITHUB_REPO", "")
        self.token = token or os.environ.get("GITHUB_TOKEN", "")

        if not self.dry_run:
            if not self.repo_name:
                raise ValueError("GITHUB_REPO env var or repo_name must be set when dry_run is False")
            if not self.token:
                raise ValueError("GITHUB_TOKEN env var or token must be set when dry_run is False")

        self._client: Any = None

    def _get_client(self) -> Any:
        """Lazy load PyGithub client."""
        if self._client is None:
            try:
                from github import Github  # type: ignore[import-not-found]
            except ImportError as e:
                raise ImportError(
                    "PyGithub is required for GitHub integration. "
                    "Install with: pip install PyGithub"
                ) from e
            self._client = Github(self.token)
        return self._client

    async def create_branch(self, branch_name: str) -> None:
        """Create a new branch from default branch."""
        if self.dry_run:
            await logger.ainfo("[DRY RUN] Would create branch", branch_name=branch_name)
            return

        try:
            gh = self._get_client()
            repo = gh.get_repo(self.repo_name)
            default_branch = repo.default_branch
            sb = repo.get_branch(default_branch)
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)
            await logger.ainfo("Created git branch", branch_name=branch_name, base=default_branch)
        except Exception as e:
            await logger.aerror("Failed to create git branch", branch_name=branch_name, error=str(e))
            raise

    async def commit_changes(
        self,
        branch_name: str,
        commit_message: str,
        file_changes: dict[str, str],
    ) -> None:
        """Commit file changes to a branch using GitHub Contents API."""
        if self.dry_run:
            await logger.ainfo(
                "[DRY RUN] Would commit changes",
                branch_name=branch_name,
                message=commit_message,
                files=list(file_changes.keys()),
            )
            return

        try:
            gh = self._get_client()
            repo = gh.get_repo(self.repo_name)
            for path, content in file_changes.items():
                try:
                    # Check if file exists to update
                    contents = repo.get_contents(path, ref=branch_name)
                    # If same content, skip committing
                    import base64
                    decoded = base64.b64decode(contents.content).decode("utf-8")
                    if decoded == content:
                        await logger.ainfo("Content unchanged, skipping commit", path=path)
                        continue

                    repo.update_file(
                        path=path,
                        message=f"{commit_message} (update {path})",
                        content=content,
                        sha=contents.sha,
                        branch=branch_name,
                    )
                    await logger.ainfo("Updated file in branch", path=path, branch=branch_name)
                except Exception:
                    # File does not exist, create it
                    repo.create_file(
                        path=path,
                        message=f"{commit_message} (create {path})",
                        content=content,
                        branch=branch_name,
                    )
                    await logger.ainfo("Created file in branch", path=path, branch=branch_name)
        except Exception as e:
            await logger.aerror("Failed to commit changes", branch_name=branch_name, error=str(e))
            raise

    async def create_pull_request(
        self,
        branch_name: str,
        title: str,
        body: str,
    ) -> str:
        """Create a PR from branch to default branch."""
        if self.dry_run:
            await logger.ainfo(
                "[DRY RUN] Would create Pull Request",
                branch=branch_name,
                title=title,
                body=body[:200] + "..." if len(body) > 200 else body,
            )
            return "https://github.com/dry-run/repo/pull/mock"

        try:
            gh = self._get_client()
            repo = gh.get_repo(self.repo_name)
            default_branch = repo.default_branch
            pr = repo.create_pull(
                title=title,
                body=body,
                base=default_branch,
                head=branch_name,
            )
            await logger.ainfo(
                "Created Pull Request successfully",
                number=pr.number,
                url=pr.html_url,
            )
            return pr.html_url  # type: ignore[no-any-return]
        except Exception as e:
            await logger.aerror("Failed to create pull request", branch=branch_name, error=str(e))
            raise
